step 1: scene setup
decentraland/hammurabi pull request #2
Opened 2023-02-19 20:48 UTC by menduz

2023-02-19 22:44 UTC, eordano requested changes
Please rename `test-scene` for `example-scene`

2023-03-09 20:26 UTC, eordano requested changes

2023-03-09 20:26 UTC, eordano commented on example-scene/README.md
> +# SDK7 Test scene
Could you please write a descriptive README of what the example scene does?

2026-08-05 13:58 UTC, closed without merging

2026-08-06 13:29 UTC, menduz commented
@charly-bg please do not close the prs of this repository. they tell a story, revert when possible please